### ISSUE TITLE
Добавление возможности поставить свой сид для генерации/апскейла изображения

### ISSUE THREAD

**Issue by egorbabushka** [Pozaza/DeepFloyd-Unofficial-API#2]
предлагаю дополнительно принимать сид генерации в качестве необязательного аргумента

**Comment by Pozaza** [comment]
Реализовал: [985e8ed](https://github.com/Pozaza/DeepFloyd-Unofficial-API/commit/985e8ed8554d4670bdab7b36a0538967493a9c86)
